### ISSUE TITLE
Setup initial project

### ISSUE THREAD

**Issue by usatko** [MediusInc/slotex-nlp-web#1]
* init project with Vaadin 13 UI framework with Spring boot framework 
https://vaadin.com/blog/spring-boot-a-perfect-platform-for-a-vaadin-ui

**Comment by usatko** [comment]
@MarkJuvan @JakobBernik any progress? Do you need additional help on this? 

Here is your mentor @cotnic . Maybe you should do it together.

**Comment by cotnic** [comment]
@MarkJuvan and @JakobBernik maybe I could setup the initial Maven project than everything else you can do. Such as add the dependencies and setup the structure of the java packages and so on. 

Are you ok with it?

**Comment by JakobBernik** [comment]
@cotnic I can push my inital project to my repository if that is ok, otherwise I am ok with it.

**Comment by cotnic** [comment]
yes, sure. Push it and send a PR (pull request) to this repository. Than we can look over and improve it if needed.

**Comment by JakobBernik** [comment]
I sent it.

**Comment by cotnic** [comment]
This issue is closed.
