### ISSUE TITLE
Page with initial data

### ISSUE THREAD

**Issue by cotnic** [MediusInc/slotex-nlp-web#6]
Please implement the page which will present the initial data about health of the slotex-nlp-core microservice.

Endpoint in the slotex-nlp-core is /actuator

First you'll have to create a Page which will represent the data provided by the endpoint. Then you'll have to implement the service which will make a GET HTTP request to the REST service endpoint called /actuator. When you retrieve the JSON Data you have to make it visible for the end user.

**Comment by cotnic** [comment]
@MarkJuvan and @JakobBernik will you two do this together or will one take this issue and we provide a new one so both of you can work on different tasks so the previous situation where you both did the same thing does not happen again?

CC @usatko

**Comment by JakobBernik** [comment]
@cotnic I'll take this issue.

**Comment by null-cell** [comment]
Agreed

**Comment by usatko** [comment]
What is the status with this issue?

**Comment by cotnic** [comment]
This issue is implemented by @JakobBernik. 

Closing.
